// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqxutjednlppvpsvbbbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxeHV0amVkbmxwcHZwc3ZiYmJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjM1NjIsImV4cCI6MjA2NTI5OTU2Mn0.WIkHFe8ea-VkMD64pX8lNybnx-PhqoMDVNLqzePoCto";
const SERVICE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxeHV0amVkbmxwcHZwc3ZiYmJvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0OTcyMzU2MiwiZXhwIjoyMDY1Mjk5NTYyfQ.Pc5pUQD4qBmnBJXo1e_UZ6CyNQuhUpjjUC6iefwvKb0'
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL,SERVICE_KEY);